In [ ]:
# !pip install pandas numpy scikit-learn matplotlib seaborn joblib

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [21]:
df = pd.read_csv("Loan_Default.csv")

In [22]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [23]:
df.shape

(255347, 18)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

In [25]:
df.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [26]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

In [36]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df = df.drop_duplicates()

In [39]:
df["Default"].value_counts()

Default
0    225694
1     29653
Name: count, dtype: int64

In [51]:
X = df.drop(["LoanID", "Default"], axis=1)
y = df["Default"]

In [52]:
y

0         0
1         0
2         1
3         0
4         0
         ..
255342    0
255343    1
255344    0
255345    0
255346    0
Name: Default, Length: 255347, dtype: int64

In [53]:
X.select_dtypes(include="object").columns

Index([], dtype='object')

In [62]:
## for Employment Type
X["EmploymentType"] = X["EmploymentType"].map({
    "Unemployed": 0,
    "Part-time": 1,
    "Full-time": 2,
    "Self-employed": 3
})

In [63]:
X["MaritalStatus"] = X["MaritalStatus"].map({
    "Single": 0,
    "Married": 1,
    "Divorced": 2
})

In [64]:
X["HasMortgage"] = X["HasMortgage"].map({
    "No": 0,
    "Yes": 1
})

In [65]:
X["HasDependents"] = X["HasDependents"].map({
    "No": 0,
    "Yes": 1
})

In [66]:
## for Loan Purpose
X["LoanPurpose"] = X["LoanPurpose"].map({
    "Auto": 0,
    "Business": 1,
    "Education": 2,
    "Home": 3,
    "Other": 4
})

In [67]:
## for Has Co-Signer
X["HasCoSigner"] = X["HasCoSigner"].map({
    "No": 0,
    "Yes": 1
})

In [68]:
## for education cols
X["Education"] = X["Education"].map({
    "High School": 0,
    "Bachelor's": 1,
    "Master's": 2,
    "PhD": 3
})

In [69]:
X.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,56,85994,50587,520,80,4,15.23,36,0.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,69,50432,124440,458,15,1,4.81,60,0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,46,84208,129188,451,26,3,21.17,24,0.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,32,31713,44799,743,0,3,7.07,24,0.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60,20437,9139,633,8,4,6.51,48,0.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
X.dtypes

Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education         float64
EmploymentType    float64
MaritalStatus     float64
HasMortgage       float64
HasDependents     float64
LoanPurpose       float64
HasCoSigner       float64
dtype: object